#!/usr/bin/env python3
"""A place-and-route harness around any module, for a design small enough
to route and big enough to test the packer on real logic.

It is cft-fp256's hw/openxc7/gen_harness.py (which writes one for cft_krnl)
made general: the port list comes from a Yosys JSON of the module
elaborated with its parameters, so every width is Yosys's own, never read
by hand. Every input but the clock is driven from one register chain fed
by the pin `sin`, the reset (if named) through a two-flop synchroniser from
`rst_n_pin`, and every output bit is XOR-folded six at a time, registered
at each level, into the pin `sout`. The clock arrives as the LVDS pair
clk_p/clk_n through IBUFDS and BUFG. The pins are cft-fp256's
hw/openxc7/cft_pnr_harness.xdc: the KC705 demo's clock pair and three
bank-33 LED pins. A bitstream built from it must never be loaded onto a
board.

usage: harness.py PORTS_JSON MODULE OUT.sv CLOCK_PORT [RESET_PORT] [-p NAME=VALUE ...]

PORTS_JSON: yosys -p "read_verilog -defer -sv ...; hierarchy -top MODULE
-chparam NAME VALUE ...; proc; write_json PORTS_JSON". The -p overrides go
into the instantiation and must be the -chparam values the JSON was made
with.
"""
import json
import sys

args = sys.argv[1:]
params = []
while "-p" in args:
    i = args.index("-p")
    params.append(args[i + 1])
    del args[i:i + 2]
ports_json, module, out, clock = args[:4]
reset = args[4] if len(args) > 4 else None

mods = json.load(open(ports_json))["modules"]
# the elaborated module: by name, else the one Yosys marks top (a
# parameterised top is renamed "$paramod...")
m = mods.get(module)
if m is None:
    tops = [v for k, v in mods.items() if module in k and int(v.get("attributes", {}).get("top", "0"), 2) == 1]
    m = tops[0] if len(tops) == 1 else None
if m is None:
    sys.exit(f"no module {module} in {ports_json}: {sorted(mods)[:8]}")
ports = [(n, p["direction"], len(p["bits"])) for n, p in m["ports"].items()]
if clock not in {n for n, _, _ in ports}:
    sys.exit(f"{module} has no port {clock}")
ins = [(n, w) for n, d, w in ports if d == "input" and n not in (clock, reset)]
outs = [(n, w) for n, d, w in ports if d == "output"]
if any(d == "inout" for _, d, _ in ports):
    sys.exit(f"{module} has an inout port; this harness drives inputs and folds outputs only")
nin = sum(w for _, w in ins)
nout = sum(w for _, w in outs)

L = []
L.append(f"// GENERATED by dense/harness.py from {module}'s ports ({ports_json}) - do not edit.")
L.append("// A place-and-route harness, not a platform: its bitstream must never be loaded onto a board.")
L.append(f"// Inputs: {len(ins)} ports, {nin} bits. Outputs: {len(outs)} ports, {nout} bits.")
L.append("`default_nettype none")
L.append("module harness_top (input wire clk_p, input wire clk_n, input wire rst_n_pin, input wire sin, "
         "output wire sout);")
L.append("  wire clk_ibufg, clk;")
L.append("  IBUFDS ibuf_inst (.I(clk_p), .IB(clk_n), .O(clk_ibufg));")
L.append("  BUFG   bufg_inst (.I(clk_ibufg), .O(clk));")
L.append("  reg [1:0] rst_sync = 2'b00;")
L.append("  always @(posedge clk) rst_sync <= {rst_sync[0], rst_n_pin};")
L.append(f"  reg [{nin - 1}:0] kin = {nin}'d0;")
L.append(f"  always @(posedge clk) kin <= {{kin[{nin - 2}:0], sin}};" if nin > 1 else "  always @(posedge clk) kin <= sin;")
L.append(f"  wire [{nout - 1}:0] kout;")
ptxt = ", ".join(f".{p.split('=')[0]}({p.split('=', 1)[1]})" for p in params)
L.append(f"  {module} {'#(' + ptxt + ') ' if ptxt else ''}u_dut (")
conns = [f"    .{clock}(clk)"]
if reset:
    conns.append(f"    .{reset}(rst_sync[1])")
lo = 0
for n, w in ins:
    conns.append(f"    .{n}(kin[{lo + w - 1}:{lo}])")
    lo += w
lo = 0
for n, w in outs:
    conns.append(f"    .{n}(kout[{lo + w - 1}:{lo}])")
    lo += w
L.append(",\n".join(conns))
L.append("  );")
# fold six at a time, registered at each level
L.append("  integer i;")
level, width, src = 0, nout, "kout"
body = []
while width > 1:
    level += 1
    groups = (width + 5) // 6
    padded = groups * 6
    L.append(f"  wire [{padded - 1}:0] p{level} = {{{{{padded - width}{{1'b0}}}}, {src}}};" if padded > width
             else f"  wire [{padded - 1}:0] p{level} = {src};")
    L.append(f"  reg  [{groups - 1}:0] x{level};")
    body.append(f"    for (i = 0; i < {groups}; i = i + 1) x{level}[i] <= ^p{level}[i*6 +: 6];")
    src, width = f"x{level}", groups
L.append("  always @(posedge clk) begin")
L.extend(body)
L.append("  end")
L.append(f"  assign sout = {src}[0];" if level else "  assign sout = kout[0];")
L.append("endmodule")
L.append("`default_nettype wire")
open(out, "w").write("\n".join(L) + "\n")
print(f"{out}: {module}, {len(ins)} input ports / {nin} bits, {len(outs)} output ports / {nout} bits, "
      f"{level} fold levels")
